> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [21]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [4]:
# List of functions explained 
function1 = np.shape  # (change this)
function2 = np.transpose
function3 = np.arange
function4 = np.argmax
function5 = np.std

## Function 1 - np.shape

Add some explanation about the function in your own words

The shape method in numpy looks at a numpy array and returns the number of rows and columns in that array for example in the array below `arr1` has 2 rows and 2 columns while `arr2` has 2 rows and 3 columns

In [2]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

print(np.shape(arr1))
print(np.shape(arr2))

(2, 2)
(2, 3)


This example generate random interger from 2 to 10 and the shape method is used to return the shape

In [3]:
# Example 2 - working
arr3 = np.random.randint(2, 10, (3,4))
print(arr3.shape)

(3, 4)


Explanation about example
np.shape will fall to work once a second argument is introduced it does not take more than one argument

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]


np.shape(arr1, 1)

TypeError: _shape_dispatcher() takes 1 positional argument but 2 were given

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - Transpose

Transpose is used to rearrange an array such that the row becomes the columns and columns becomes the row. It can also be used for interchanging axes of an array
for instance the shape arr3 is 3, 4 after transposing it the shape changes to 4,3
Add some explanations

In [5]:
# Example 1 - working
arr3 = np.random.randint(2, 10, (3,4))
print(arr3)
print('*'*42)
print(np.transpose(arr3))

[[9 5 8 4]
 [9 9 9 2]
 [3 5 2 8]]
******************************************
[[9 9 3]
 [5 9 5]
 [8 9 2]
 [4 2 8]]


Explanation about example
In the example below an array of shape (2,3,5) is transpose into an array of shape (3,5,2). Hence we can see that transpose is basically used for interchanging of axes

In [6]:
# Example 2 - working
arr4 = np.random.randint(1, 6, (2,3,5))
print(arr4)
print('*'*42)
print(np.transpose(arr4, (1,2,0)))

[[[1 1 2 2 3]
  [5 2 2 1 4]
  [2 2 1 1 4]]

 [[4 5 3 2 1]
  [4 2 2 5 4]
  [1 2 3 2 3]]]
******************************************
[[[1 4]
  [1 5]
  [2 3]
  [2 2]
  [3 1]]

 [[5 4]
  [2 2]
  [2 2]
  [1 5]
  [4 4]]

 [[2 1]
  [2 2]
  [1 3]
  [1 2]
  [4 3]]]


Explanation about example
there is an error in the code below because if we look at the shape of arr3 which is (3,4) ie. two dimensional array but for the axes argument it is recieve a one dimension hence the dimension of the array we are transposing must be the same as the dimension we will pass into the axes argument of transpose

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
np.transpose(arr3, 1)

ValueError: axes don't match array

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - Arange

Add some explanations
np.arange is used to generate a range of number which has a start(starting value), end(stopping value), step(how should the increment be performed)

In [8]:
# Example 1 - working
arr5 = np.arange(1, 7)
print(arr5)

[1 2 3 4 5 6]


Explanation about example
generating an range of number from 1 to 10 and increasing it be 2

In [9]:
# Example 2 - working
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Explanation about example
Sometimes we might not get the expected result if there are error in the argument just like the one below

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(1, 4, -1)

array([], dtype=int32)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - np.argmax

This function helps take the index of maximum value and it can also be done along axes

In [14]:
# Example 1 - working
arr6 = np.arange(1, 13).reshape(3,4)
np.argmax(arr6)

11

Explanation about example
This function find the index of the maximum value along the first axis which is alone the row

In [15]:
# Example 2 - working
np.argmax(arr6, axis = 1)

array([3, 3, 3], dtype=int64)

Explanation about example
This error is generated because the program was told to find the maximum value along the 3 axis which does not exist 

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
np.argmax(arr6, axis = 3)

AxisError: axis 3 is out of bounds for array of dimension 2

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - np.std

Add some explanations
This function is mostly used for descriptive statistics to check for variance in data arranged along rows and columns

In [17]:
# Example 1 - working
np.std(arr6)

3.452052529534663

Explanation about example

below we find the standard deviation along the first axis which is along the row

In [18]:
# Example 2 - working
np.std(arr6, 1)

array([1.11803399, 1.11803399, 1.11803399])

Explanation about example
In the example below we try to find the standard deviation along the 3 axis whereas how data only has 2 axis which is 0,1

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
np.std(arr6, 3)

AxisError: axis 3 is out of bounds for array of dimension 2

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'